docs/team/mingyuanc.md, docs/team/nereuswb922.md, docs/team/ngchunman.md, docs/team/nid21cs.md, docs/team/zannloo.md
Include only the headings for the skeletal PPP.
"to be added soon" are placeholders for content.
=> Add a skeletal PPP

src/main/java/seedu/address/model/profbook/Group.java, src/main/java/seedu/address/model/profbook/ProfBook.java, src/main/java/seedu/address/model/profbook/StateManager.java, src/main/java/seedu/address/model/profbook/Student.java, src/main/java/seedu/address/model/taskmanager/Task.java, src/main/java/seedu/address/model/taskmanager/TaskList.java
=> Generate skeleton code for required class

src/main/java/seedu/address/model/profbook/ChildrenManager.java, src/main/java/seedu/address/model/profbook/Group.java, src/main/java/seedu/address/model/profbook/IChildElement.java, src/main/java/seedu/address/model/profbook/Student.java, src/main/java/seedu/address/model/statemanager/GroupOperation.java, src/main/java/seedu/address/model/statemanager/IChildOperation.java, src/main/java/seedu/address/model/statemanager/RootOperation.java, src/main/java/seedu/address/model/taskmanager/TaskList.java
Fixes #82
- Implemented updateChild
- Implemented clone
- Optimised some of taskmanager code
=> 82-add-updateChild-clone

src/main/java/seedu/address/logic/newcommands/Command.java, src/main/java/seedu/address/logic/newcommands/CommandResult.java, src/main/java/seedu/address/logic/newcommands/CreateDeadlineForGroupCommand.java, src/main/java/seedu/address/logic/newcommands/CreateGroupCommand.java, src/main/java/seedu/address/logic/newcommands/CreateTodoForGroupCommand.java, src/main/java/seedu/address/logic/newcommands/MoveStudentToGroupCommand.java, src/main/java/seedu/address/logic/newcommands/exceptions/CommandException.java
Create a new package, newcommands, for the new command classes ( CreateDeadlineForGroupCommand, CreateGroupCommand, CreateTodoForGroupCommand and MoveStudentToGroupCommand).
=> Create initial command class skeletons

src/main/java/seedu/address/model/path/AbsolutePath.java, src/main/java/seedu/address/model/path/Path.java, src/main/java/seedu/address/model/path/RelativePath.java, src/main/java/seedu/address/model/path/element/PathElement.java
=> Implement equals and hashCode method for Path class

src/main/java/seedu/address/model/id/GroupId.java, src/main/java/seedu/address/model/id/Id.java, src/main/java/seedu/address/model/id/StudentId.java, src/main/java/seedu/address/model/path/AbsolutePath.java, src/main/java/seedu/address/model/path/Path.java, src/main/java/seedu/address/model/path/element/PathElement.java, src/main/java/seedu/address/model/profbook/Student.java, src/main/java/seedu/address/model/statemanager/StateManager.java, src/main/java/seedu/address/model/statemanager/StudentOperation.java, src/test/java/seedu/address/model/path/AbsolutePathTest.java
Fix #86 #94 
- Add logic to resolve path start with ~/
- Move directory related method to parent Path class as RelativePath also need these methods
- Remove checked exception in id factory method
- Fix import error in student class
=> Fix #86 #94

src/main/java/seedu/address/model/profbook/ChildrenManager.java, src/main/java/seedu/address/model/statemanager/GroupOperation.java, src/main/java/seedu/address/model/statemanager/IChildOperation.java, src/main/java/seedu/address/model/statemanager/RootOperation.java
=> Implement requested functions

src/main/java/seedu/address/model/taskmanager/TaskList.java, src/test/java/seedu/address/model/taskmanager/TaskListTest.java
Add testing for TaskList methods and added size method into TaskList for testing purposes
=> 98-Add-Junit-Testing-for-TaskList

src/main/java/seedu/address/model/profbook/TaskListManager.java, src/main/java/seedu/address/model/taskmanager/Deadline.java, src/main/java/seedu/address/model/taskmanager/Task.java, src/main/java/seedu/address/model/taskmanager/TaskList.java, src/main/java/seedu/address/model/taskmanager/ToDo.java
- Checks equality of every object in List both deadline and ToDo 
- Checks fields within both Deadline and ToDo
=> Add Equals method to TaskList and related classes

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/ProfBookLogicManager.java, src/main/java/seedu/address/logic/newcommands/ChangeDirectoryCommand.java, src/main/java/seedu/address/logic/newcommands/Command.java, src/main/java/seedu/address/logic/newcommands/CreateDeadlineCommand.java, src/main/java/seedu/address/logic/newcommands/CreateGroupCommand.java, src/main/java/seedu/address/logic/newcommands/CreateStudentCommand.java, src/main/java/seedu/address/logic/newcommands/CreateTodoCommand.java, src/main/java/seedu/address/logic/newcommands/MoveStudentToGroupCommand.java, src/main/java/seedu/address/logic/parser/newcommandparser/ChangeDirectoryCommandParser.java, src/main/java/seedu/address/logic/parser/newcommandparser/ProfBookParser.java, src/main/java/seedu/address/model/profbook/ChildrenManager.java, src/main/java/seedu/address/model/profbook/Group.java, src/main/java/seedu/address/model/statemanager/State.java, src/main/java/seedu/address/model/statemanager/StateManager.java, src/main/java/seedu/address/ui/CommandBox.java, src/main/java/seedu/address/ui/GroupCard.java, src/main/java/seedu/address/ui/ItemListPanel.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/StudentCard.java, src/main/java/seedu/address/ui/UiManager.java, src/main/resources/view/GroupCard.fxml, src/main/resources/view/ItemListPanel.fxml, src/main/resources/view/MainWindow.fxml, src/main/resources/view/StudentCard.fxml, src/test/java/seedu/address/logic/newcommands/CreateDeadlineCommandTest.java, src/test/java/seedu/address/logic/newcommands/CreateStudentCommandTest.java
- Use State class to store current app state
- Refactor command execute method to take in State as argument
- Create generic ItemListPanel
- Create UI for Student and Group
- Use ObservableList to store children
- Refactor Main App, Main Window
- Implement cd command
=> Refactor GUI

build.gradle
=> V1.2 Release

docs/UserGuide.md, src/main/java/seedu/address/logic/parser/Option.java, src/main/java/seedu/address/model/id/GroupId.java, src/main/java/seedu/address/model/id/Id.java, src/main/java/seedu/address/model/id/StudentId.java, src/main/java/seedu/address/model/util/SampleProfBook.java, src/test/java/seedu/address/logic/newcommands/CommandTestUtil.java, src/test/java/seedu/address/logic/newcommands/CreateDeadlineCommandTest.java, src/test/java/seedu/address/logic/newcommands/CreateStudentCommandTest.java, src/test/java/seedu/address/logic/newcommands/CreateTodoCommandTest.java, src/test/java/seedu/address/logic/newcommands/DeleteForStudentsAndGroupsCommandTest.java, src/test/java/seedu/address/logic/newcommands/MoveStudentToGroupCommandTest.java, src/test/java/seedu/address/model/path/AbsolutePathTest.java, src/test/java/seedu/address/statemanager/ChildOperationTest.java, src/test/java/seedu/address/statemanager/TaskOperationTest.java, src/test/java/seedu/address/testutil/GroupBuilder.java, src/test/java/seedu/address/testutil/StudentBuilder.java, src/test/java/seedu/address/testutil/TypicalStudents.java
- change format to 4 digits number follow by any letter
=> Edit id format

src/main/java/seedu/address/logic/newcommands/DeleteTaskCommand.java, src/main/java/seedu/address/logic/parser/newcommandparser/DeleteTaskCommandParser.java, src/main/java/seedu/address/logic/parser/newcommandparser/ProfBookParser.java, src/main/java/seedu/address/model/profbook/TaskListManager.java, src/main/java/seedu/address/model/statemanager/ITaskOperations.java, src/main/java/seedu/address/model/statemanager/StateManager.java, src/main/java/seedu/address/model/statemanager/TaskOperation.java, src/main/java/seedu/address/model/taskmanager/Deadline.java, src/main/java/seedu/address/model/taskmanager/ToDo.java, src/test/java/seedu/address/logic/newcommands/CommandTestUtil.java, src/test/java/seedu/address/logic/newcommands/CreateDeadlineCommandTest.java, src/test/java/seedu/address/logic/newcommands/CreateTodoCommandTest.java, src/test/java/seedu/address/logic/newcommands/DeleteTaskCommandTest.java, src/test/java/seedu/address/logic/parser/newcommandparser/DeleteTaskCommandParserTest.java, src/test/java/seedu/address/testutil/TypicalIndexes.java
=> Implement delete task command

src/main/java/seedu/address/Main.java, src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/ProfBookLogicManager.java, src/main/java/seedu/address/model/taskmanager/Deadline.java, src/test/java/seedu/address/logic/newcommands/CreateDeadlineCommandTest.java, src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Updated Task classes and removed comments
=> 145 update task classes

docs/diagrams/StorageClassDiagram.puml, src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/storage/JsonProfBookStorage.java, src/main/java/seedu/address/storage/ProfBookStorageManager.java, src/main/java/seedu/address/storage/Storage.java
=> Improve OOP - Storage

src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/field/EditGroupDescriptor.java, src/main/java/seedu/address/model/task/Deadline.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/CreateDeadlineCommandTest.java, src/test/java/seedu/address/logic/commands/CreateGroupCommandTest.java, src/test/java/seedu/address/logic/commands/CreateStudentCommandTest.java, src/test/java/seedu/address/logic/commands/CreateTodoCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteForStudentsAndGroupsCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/MarkCommandTest.java, src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java, src/test/java/seedu/address/storage/JsonAdaptedGroupTest.java, src/test/java/seedu/address/storage/JsonAdaptedRootTest.java, src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java, src/test/java/seedu/address/testutil/GroupBuilder.java, src/test/java/seedu/address/testutil/RootBuilder.java, src/test/java/seedu/address/testutil/StudentBuilder.java, src/test/java/seedu/address/testutil/TaskListBuilder.java, src/test/java/seedu/address/testutil/TypicalGroups.java, src/test/java/seedu/address/testutil/TypicalRoots.java, src/test/java/seedu/address/testutil/TypicalStudents.java, src/test/java/seedu/address/testutil/TypicalTasks.java
- Add more test util to reduce duplicates
- Refactor test cases to use newly added test util
=> Create test util

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/CreateGroupCommand.java, src/main/java/seedu/address/logic/commands/CreateStudentCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/field/EditGroupDescriptor.java, src/main/java/seedu/address/model/profbook/Email.java, src/main/java/seedu/address/model/profbook/Name.java, src/test/java/seedu/address/logic/commands/CreateGroupCommandTest.java, src/test/java/seedu/address/logic/commands/CreateStudentCommandTest.java
Command Edited: (So always check whether id is used)
1. CreateStudent
2. CreateGroup
3. Edit
For Edit Command:
1. Add check for edited entitiy has the same info before edited (User pass in the same value)
=> Fix bugs check duplicates id in ProfBook

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java, src/main/java/seedu/address/logic/parser/CreateDeadlineCommandParser.java, src/main/java/seedu/address/logic/parser/CreateGroupCommandParser.java, src/main/java/seedu/address/logic/parser/CreateStudentCommandParser.java, src/main/java/seedu/address/logic/parser/CreateTodoCommandParser.java, src/main/java/seedu/address/logic/parser/DeleteForStudentsAndGroupsCommandParser.java, src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/MarkCommandParser.java, src/main/java/seedu/address/logic/parser/MoveStudentToGroupCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/ShowChildrenListCommandParser.java, src/main/java/seedu/address/logic/parser/ShowTaskListCommandParser.java, src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java, src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java, src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java, src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
- to check all options in argument are valid
=> Validate options

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/CreateStudentCommandParser.java, src/main/java/seedu/address/model/ChildOperation.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/TaskOperation.java, src/main/java/seedu/address/model/profbook/ChildrenAndTaskListManager.java, src/main/java/seedu/address/model/profbook/ChildrenManager.java, src/main/java/seedu/address/model/profbook/IChildrenManager.java, src/main/java/seedu/address/model/task/ITaskListManager.java, src/main/java/seedu/address/model/task/ReadOnlyTaskList.java, src/main/java/seedu/address/model/task/TaskListManager.java, src/main/java/seedu/address/storage/JsonAdaptedGroup.java, src/main/java/seedu/address/storage/JsonAdaptedStudent.java, src/test/java/seedu/address/logic/commands/MoveStudentToGroupCommandTest.java, src/test/java/seedu/address/logic/parser/CreateStudentCommandParserTest.java, src/test/java/seedu/address/statemanager/ChildOperationTest.java, src/test/java/seedu/address/statemanager/TaskOperationTest.java, src/test/java/seedu/address/testutil/StudentBuilder.java, src/test/java/seedu/address/testutil/TypicalTasks.java
- Add ITaskListManager
- Add IChildrenManager
=> Enhance TaskList and Children Manager

docs/team/ngchunman.md
- Introduce class enhancements
- Update Developer Guide Contributions
- Update User Guide Contributions
- Add Team-Based Task Contributions
=> Final Edit PPP
